<?php echo $this->action('settings', 'training'); ?>
<?php if ( !empty($this->translate) || !empty($this->speech) ): ?>
<div class="training-first">
<?php if ( !empty($this->translate) ): ?>
<h3 style="font-size: 20px;">Как переводится <span style="color:#8E3835">"<?php echo $this->translate['translate']; ?>"</span>?</h3>
<?php endif; ?>
<?php if ( !empty($this->speech) ): ?>
<h3 style="font-size: 20px;">
Прослушайте и укажите слово<br/><!--<a class="play" href="<?php echo $this->speech['url'];?>">Прослушать слово</a>-->
<p style="margin-top:0px;">
<object id="player" type="application/x-shockwave-flash" data="/swf/ump3player_500x70.swf" height="45" width="300"><param name="FlashVars" value="way=<?php echo $this->speech['url'];?>&amp;swf=/swf/ump3player_500x70.swf&amp;w=1&amp;h=1&amp;time_seconds=164&amp;autoplay=1&amp;q=&amp;skin=grey&amp;volume=70&amp;comment=" /></object>
</p>
</h3>
<?php endif; ?>
</div>
<?php if ( !empty($this->words) ): ?>
<div class="third-div">
<?php foreach ( $this->words as $word ): ?>
<p class="answer"><a class="second-answer<?php echo $word['true'] == 'true' ? ' true' : ''?>" href="<?php echo $this->url(array('controller' => 'training', 'action' => 'second', 'answer' => $word['id']), null, true)?>"><?php echo $word['word']; ?></a></p>
<?php endforeach; ?>
<?php endif; ?>
</div>
<a class="continue" href="<?php echo $this->url(array('controller' => 'training', 'action' => 'second', 'next' => 1), null, true)?>">Пропустить</a>
<?php endif; ?>

<?$this -> headScript() -> captureStart();?>

$(document).ready(function(){

    $('.answer a').mouseover(function(){

	$(this).Animator().addAnimation({'padding-top': '20px', 'padding-bottom': '20px', 'font-size': '25px', 'border-color': '#000000'}, 300);
    });

    $('.answer a').mouseout(function(){

	$(this).Animator().addAnimation({'padding-top': '10px', 'padding-bottom': '10px', 'font-size': '16px', 'border-color': '#cccccc'}, 100);
    });

    $('.second-answer').click(function(){

	$('.continue').hide();

	    if ( $(this).hasClass('true') ) {
		$(this).parent().addClass('true-answer');
	    }
	    else {
		$(this).parent().addClass('false-answer');
	    }

	    $.getJSON($(this).attr('href'), function(data) {
		if ( data ) {
		    window.location.href=data;
		}
		else
		    window.location.reload();
	    });

	    return false;

    });
});

<?$this -> headScript() -> captureEnd();?>