<h3 style="margin-left:10px;">Форма обратной связи</h3>
<form action="" method="post">
<table style="width:100%">
<tr>
<td>Имя:</td>
<td><input style="width:100%" type="text" name="name" value="<?php echo !empty($this->values['name']) ? $this->values['name'] : '' ?>"/>
<?php if ( !empty($this->errors['name']) ): ?>
<div class="errors"><?php echo implode($this->errors['name'], '<br/>')?></div>
<?php endif; ?>
</td>
</tr>
<tr>
<td>Е-майл:</td>
<td><input style="width:100%" type="text" name="email" value="<?php echo !empty($this->values['email']) ? $this->values['email'] : '' ?>"/>
<?php if ( !empty($this->errors['email']) ): ?>
<div class="errors"><?php echo implode($this->errors['email'], '<br/>')?></div>
<?php endif; ?>
</td>
</tr>
<tr>
<td>Тема:</td>
<td><input style="width:100%" type="text" name="theme" value="<?php echo !empty($this->values['theme']) ? $this->values['theme'] : '' ?>"/>
<?php if ( !empty($this->errors['theme']) ): ?>
<div class="errors"><?php echo implode($this->errors['theme'], '<br/>')?></div>
<?php endif; ?>
</td>
</tr>
<tr>
<td>Сообщение:</td>
<td><textarea style="width:100%;height:80px;" name="text"><?php echo !empty($this->values['text']) ? $this->values['text'] : '' ?></textarea>
<?php if ( !empty($this->errors['text']) ): ?>
<div class="errors"><?php echo implode($this->errors['text'], '<br/>')?></div>
<?php endif; ?>
</td>
</tr>
</table>
<p style="text-align:right"><input type="submit" value="Отправить" /></p>
</form>